# Configuration Render.com pour T2C Now
# Voir: https://render.com/docs/blueprint-spec

services:
  - type: web
    name: t2c-now
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: GTFS_RT_URL
        value: https://proxy.transport.data.gouv.fr/resource/t2c-clermont-gtfs-rt-trip-update
